### PR TITLE
Use block bindings instead of custom blocks for some actors / movies data.

### PR DESCRIPTION
**Pull request by cbravobernal**
Before block bindings, all the movies and actors data were coming from post-meta in form of custom blocks.

This PR replaces them with block bindings. We want this project to be an example of all developer tools WordPress is now providing.

In a future, ideally, most of this data should not be custom sources, but just meta data with paragraphs connected to that post metadata. But the custom fields are protected (unprotecting them would imply some big changes on the database) and also have some tweaks (date formatting and that stuff, which is not yet solved in post-meta bound cases).

I will keep iterating these blocks with future developments!

### CODE REVIEW

**Review by SantosGuillamot — COMMENTED** [review]
Why are we creating a new source for each custom field? I don't think it is a pattern we should recommend. For me, ideally, we should reuse the existing post meta source. I get it won't work because the fields are protected, but maybe we need to change the database to fix that.

Using post meta will come with the benefit that it is supported in the editor, so it would be good for demos or users testing it.

Even if we don't want to go that way, I believe having a unique source that extends post meta to allow custom fields would be better.

**Comment by cbravobernal** [comment]
I didn't want to unprotect the data, as, for this case, is provided by an external source. Also, is easier to follow simple examples like this one rather than creating an "inteligent" source that provides the data depending on any option or variable.

Current movies and actors posts only contains the description of them, no the rest of the data, that's another reason I went this way.

**Comment by SantosGuillamot** [comment]
In my opinion, we shouldn't promote creating a custom source for each block when they could be abstracted. That's why we use `source_args`. It's true that in some cases we are formatting the value, but I am not sure if that's reason enough. Maybe it is a good use case to use the [new filter](https://github.com/WordPress/wordpress-develop/pull/6839) as an example?

I would also like to migrate the [`movie-data` block](https://github.com/WordPress/wp-movies-demo/blob/main/src/blocks/non-interactive/movie-data/render.php) and use bindings for language, budget, and revenue. If we have to create a new source for each meta field we want to connect to, it doesn't seem scalable.

Having said that, this is just my opinion, I'd love to hear more thoughts.

**Comment by cbravobernal** [comment]
Let's close this one and think about moving to public post metadata.

**Comment by gziolo** [comment]
Good call. Let’s rethink the approach so it serves as the example of how much you can simplify development by using the API shipped with WordPress 6.7.

**Pull request closed without merging**
